---
#playbook principal de la actividad
- name: playbook principal
  hosts: webservers
  become: yes
  tasks:
    - include: env-preparation-playbook.yml
    - include: nginx-playbook.yml
    - include: deploy-playbook.yml
  handlers:
    - include: nginx-handler.yml

...